// constants/courseConstants.js
export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSE_LIKE_SUCCESS = 'COURSE_LIKE_SUCCESS';
export const COURSE_COMMENT_SUCCESS = 'COURSE_COMMENT_SUCCESS';
export const COURSE_SHARE_SUCCESS = 'COURSE_SHARE_SUCCESS';
